# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/brent/camera_using_external_memory/camera_using_external_memory.cache/wt [current_project]
set_property parent.project_path /home/brent/camera_using_external_memory/camera_using_external_memory.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/brent/camera_using_external_memory/camera_using_external_memory.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/brent/camera_using_external_memory/debouncer.vhd
  /home/brent/camera_using_external_memory/histogram.vhd
  /home/brent/camera_using_external_memory/i2c_sender.vhd
  /home/brent/camera_using_external_memory/effects/negative.vhd
  /home/brent/camera_using_external_memory/oled_display.vhd
  /home/brent/camera_using_external_memory/ov7670_capture.vhd
  /home/brent/camera_using_external_memory/ov7670_controller.vhd
  /home/brent/camera_using_external_memory/ov7670_registers.vhd
  /home/brent/camera_using_external_memory/effects/rgb_to_gray.vhd
  /home/brent/camera_using_external_memory/effects/sad.vhd
  /home/brent/camera_using_external_memory/effects/sobel.vhd
  /home/brent/camera_using_external_memory/video.vhd
  /home/brent/camera_using_external_memory/video_timing.vhd
  /home/brent/camera_using_external_memory/effects/xor.vhd
  /home/brent/camera_using_external_memory/camera.vhd
}
read_ip -quiet /home/brent/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/ddr/ddr.xci
set_property used_in_implementation false [get_files -all /home/brent/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/ddr/ddr/user_design/constraints/ddr.xdc]
set_property used_in_implementation false [get_files -all /home/brent/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/ddr/ddr/user_design/constraints/ddr_ooc.xdc]

read_ip -quiet /home/brent/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/line_buffer/line_buffer.xci
set_property used_in_implementation false [get_files -all /home/brent/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/line_buffer/line_buffer_ooc.xdc]

read_ip -quiet /home/brent/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/brent/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/brent/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/brent/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/brent/camera_using_external_memory/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files /home/brent/camera_using_external_memory/Nexys-A7-100T-Master.xdc]


synth_design -top camera -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef camera.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file camera_utilization_synth.rpt -pb camera_utilization_synth.pb"
