# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/brent/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/line_buffer/line_buffer.xci
# IP: The module: 'line_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/brent/camera_using_external_memory/camera_using_external_memory.gen/sources_1/ip/line_buffer/line_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_buffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/brent/camera_using_external_memory/camera_using_external_memory.srcs/sources_1/ip/line_buffer/line_buffer.xci
# IP: The module: 'line_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/brent/camera_using_external_memory/camera_using_external_memory.gen/sources_1/ip/line_buffer/line_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
